#!/bin/bash
cd `dirname $0`

echo "Building..."

if [ "$1" = "-v" ]; then

    shift
    make -C ../linux/ -j 14 linux ARCH=um O=build/ && ./run-test-on-last-build "$@"

else

    make -C ../linux/ -j 14 linux ARCH=um O=build/ >/dev/null && (./run-test-on-last-build "$@" 2>&1 | sed -n '/---- Executing: .* ----/,$p' | grep -Pv 'remove_umid_dir - remove_files_and_dir failed with err = -16|System halted.')

fi